#!/bin/bash

image=$1
header=$2
all=$3

function program_is_installed {
  # set to 1 initially
  local return_=1
  # set to 0 if not found
  type $1 >/dev/null 2>&1 || { local return_=0; }
  # return value
  echo "$return_"
}

if [ "$(program_is_installed gnome-terminal)" == 1 ]; then
    gnome-terminal -e "./download_install $image $header $all"
    exit 1
fi

if [ "$(program_is_installed xfce4-terminal)" == 1 ]; then
    xfce4-terminal -e "./download_install $image $header $all"
    exit 1
fi

if [ "$(program_is_installed konsole)" == 1 ]; then
    konsole -e "./download_install $image $header $all"
    exit 1
fi

if [ "$(program_is_installed lxterminal)" == 1 ]; then
    lxterminal -e "./download_install $image $header $all"
    exit 1
fi
